import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * 三板块三条侧边栏：一条路由只显示所属板块的侧边栏。
 * - guides   指南：介绍 / 快速上手 / 第一个内容组件
 * - advanced 深入：原 Cookbook 篇章
 * - api      API 参考：TypeDoc 生成(由 docusaurus.config.ts 的 sidebarItemsGenerator 注入)
 */
const sidebars: SidebarsConfig = {
  guides: [{ type: "autogenerated", dirName: "guides" }],
  advanced: [{ type: "autogenerated", dirName: "advanced" }],
  api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
